name: bench

on:
  pull_request:
    types: [ labeled ]
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  bench:
    if: ${{ github.event.label.name == 'bench' }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}

    - name: criterion compare
      uses: boa-dev/criterion-compare-action@v3.2.4
      with:
        branchName: ${{ github.base_ref }}
        token: ${{ secrets.GITHUB_TOKEN }}
