name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-build-stable-${{ hashFiles('**/Cargo.toml') }}

    - name: build
      run: cargo build

    - name: build_tools
      run: cargo build --bin ply_to_gcloud

    - name: lint
      run: cargo clippy

    - name: test (default)
      run: cargo test

    - name: test (web)
      run: cargo test --no-default-features --features="web io_ply tooling"

    # - name: gaussian render test
    #   run: cargo run --bin test_gaussian

    # - name: radix sort test
    #   run: cargo run --bin test_radix --features="debug_gpu"


    # TODO: test wasm build, deploy, and run
