name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest]
        rust-toolchain:
          - nightly

    runs-on: ${{ matrix.os }}
    timeout-minutes: 120

    steps:
    - uses: actions/checkout@v3

    - name: Setup ${{ matrix.rust-toolchain }} rust toolchain with caching
      uses: brndnmtthws/rust-action@v1
      with:
        toolchain: ${{ matrix.rust-toolchain }}
        components: rustfmt, clippy
        enable-sccache: "true"

    - name: build
      run: cargo build

    - name: build_tools
      run: cargo build --bin ply_to_gcloud

    - name: lint
      run: cargo clippy

    - name: test (default)
      run: cargo test

    - name: test (web)
      run: cargo test --no-default-features --features="web io_ply tooling"

    # - name: gaussian render test
    #   run: cargo run --bin test_gaussian

    # - name: radix sort test
    #   run: cargo run --bin test_radix --features="debug_gpu"


    # TODO: test wasm build, deploy, and run
